### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by grimnight** [lmorg/mxtty#3]
I stumbled on this repo yesterday and it seemed interesting.
After some trouble I managed to compile it, but it doesn't start.

All I get is:
```śhell
/Dev/GHQ/github.com/lmorg/mxtty main
❯ ./mxtty
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  33 (X_GrabKey)
  Serial number of failed request:  10
  Current serial number in output stream:  11
```

Any idea what the problem is?
My OS is Ubuntu.

**Comment by lmorg** [comment]
Sounds like `F12` is bound to another application. The term should handle that gracefully but looks like it's not here. I can take a look

**Comment by lmorg** [comment]
@grimnight latest commit should start for you now

**Comment by lmorg** [comment]
> The output also doesn't look like a table, like in the screenshots.

What are you using to generate the tables? Currently only the `develop` branch of Murex is compatible with the tables. But in that version, anything that outputs a CSV "should" be converted into a table using either `format csv` or `cast csv`.

Some commands will already have a wrapper function to support csv too. For example `ps` is really just a Murex function running `ps ... | format csv`

>  How do I adjust the font, it doen't look quite right.

At the moment this can only be changed at compile time in `config/defaults.yaml`:
https://github.com/lmorg/mxtty/blob/main/config/defaults.yaml

This will become user configurable, I just haven't gotten that far yet.

Regarding the type faces, there are a few known issues:
- the rendering without ligatures is a little off. I'm not sure why.
- with ligatures ANSI colour codes are not 100% correct 100% of the time. Albeit this is just happening in a few edge cases where the shell is tested for full terminal conformity. The code behind the ligatures needs a bit of a refactor. However the actual rendering of the letters should be more accurate than without ligatures
- unicode support is almost completely missing:
    - no support for wide characters
    - no support for emojis
    - no support for alternative unicode type faces (eg to include non-Western characters)
    - no support for powerline characters
- also highlighting has blocks missing. This is a known bug and I'm 90% sure I already know what the issue is there. It should still work there, even if it's a little ugly at times

**Comment by lmorg** [comment]
> Where is a list of the keybindings?
There isn't really much in the way of keybindings at the moment. Only the following:
- [f3]: search
- [cmd/meta]+v: paste
- [f12]: show/hide window (macOS only)

Everything else is mouse / trackpad driven at the moment. But I do plan on making terminal widgets more keyboard driven.

These current bindings are hardcoded and there's no way to change them in `defaults.yaml`. That will change too.

For now, the status bar should give you an idea of what controls are available.

Tmux will have it's own keyboard controls. The terminal imports those from tmux itself, so you can reconfigure them in `.tmux.conf`. If you've not used tmux before then `[ctrl]`+`b` followed by `?` (ie `?` pressed as a second keystroke within two seconds after `[ctrl]`+`b`) should bring up a list keyboard controls available from tmux.

> Where is a list of the keybindings?

Don't apologize. I welcome any questions and feedback that comes :)

>  Mxtty looks interesting, looking forward to seeing how it ends up.

Thank you
